# Use postgres/example user/password credentials
version: '3.9'

services:
  server:
    image: cosmtrek/air
    working_dir: /app

    depends_on:
      - postgres

    ports:
      - 8000:8000

    volumes:
      - ..:/app

    command: "/bin/bash"

    environment:
      NIUO_DB_HOST: postgres
      NIUO_DB_PORT: 5432

  postgres:
    image: postgres
    restart: always

    environment:
      POSTGRES_USER: niuo
      POSTGRES_PASSWORD: niuo
      POSTGRES_DB: niuo

      PGDATA: /var/lib/postgresql/data/pgdata

    volumes:
      -  db-data:/var/lib/postgresql/data/pgdata

    ports:
      - 15432:5432

volumes:
  db-data:
    # external: true
